name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform v1.9.5
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Install Terragrunt
        run: |
          curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.67.1/terragrunt_linux_amd64 
          chmod +x terragrunt 
          sudo mv terragrunt /usr/local/bin/terragrunt

      - name: Initialize Terragrunt
        working-directory: terragrunt  # Ensure this runs in the correct directory
        run: terragrunt init

      - name: Apply Terragrunt
        working-directory: terragrunt  # Ensure this runs in the correct directory
        run: terragrunt apply -auto-approve

  python:
    name: Deploy Application Code
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the Python script
        run: python process_json.py
