name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terragrunt:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7

    - name: Install Terragrunt
      run: |
        curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.35.10/terragrunt_linux_amd64
        chmod +x terragrunt
        sudo mv terragrunt /usr/local/bin/

    - name: Initialize Terragrunt
      run: terragrunt init
      working-directory: ./terraform

    - name: Apply Terragrunt
      run: terragrunt apply -auto-approve
      working-directory: ./terraform

  deploy:
    name: Deploy Application Code
    runs-on: ubuntu-latest
    needs: terragrunt

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python process_json.py

    - name: Upload to S3
      run: |
        aws s3 cp filtered_products.json s3://daniels-s3bucket/filtered_products.json
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
