name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository to access the codebase
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Use Terragrunt Docker container and specify the command
      - name: Run Terragrunt with Docker
        run: |
          docker run --rm \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_REGION=eu-north-1 \
            -v $(pwd):/workspace \
            -w /workspace/my_terragrunt \
            alpine/terragrunt:latest terragrunt init

      - name: Apply Terragrunt with Docker
        run: |
          docker run --rm \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_REGION=eu-north-1 \
            -v $(pwd):/workspace \
            -w /workspace/my_terragrunt \
            alpine/terragrunt:latest terragrunt apply -auto-approve

  python:
    name: Deploy Application Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run the Python script
        run: python process_json.py
