name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository to access the codebase
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up the specified version of Terraform (latest stable)
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      # Step 3: Configure AWS credentials for Terraform
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # Step 4: Install Terragrunt for managing Terraform configurations
      - name: Install Terragrunt
        run: |
          curl -L -o terragrunt_bin https://github.com/gruntwork-io/terragrunt/releases/download/v0.67.1/terragrunt_linux_amd64
          chmod +x terragrunt_bin
          sudo mv terragrunt_bin /usr/local/bin/terragrunt

      - name: Set TERRAGRUNT_TFPATH
        run: |
          echo "TERRAGRUNT_TFPATH=$(which terraform)" >> $GITHUB_ENV

      # Step 5: Initialize Terragrunt to set up the working directory
      - name: Initialize Terragrunt
        working-directory: my_terragrunt
        run: TERRAGRUNT_TFPATH=$(which terraform) terragrunt init

      # Step 6: Apply Terragrunt configurations to provision infrastructure
      - name: Apply Terragrunt
        working-directory: my_terragrunt
        run: terragrunt apply -auto-approve

  python:
    name: Deploy Application Code
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      # Step 1: Checkout the repository to access the codebase
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment using the latest stable version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install Python dependencies from the requirements file
      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      # Step 4: Execute the Python script to process JSON
      - name: Run the Python script
        run: python process_json.py
