name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-22.04  # Ensure using the correct platform

    steps:
      # Step 1: Checkout the repository to access the codebase
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform with a specified version
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # Step 3: Set up Terragrunt with a specified version
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: 0.6.0

      # Step 4: Configure AWS credentials for Terraform
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # Step 5: Initialize Terragrunt
      - name: Initialize Terragrunt
        # run: terragrunt init
        run: terragrunt init --terragrunt-config ./terraform/terragrunt.hcl

      # Step 6: Apply Terragrunt configurations to provision infrastructure
      - name: Apply Terragrunt
        run: terragrunt apply -auto-approve --terragrunt-config ./terraform/terragrunt.hcl

  python:
    name: Deploy Application Code
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run the Python script
        run: python process_json.py
